[build]
command = "npm run build" # Build script for the server
functions = "./build" # Directory containing the server code
publish = "client" # Directory containing the React app build

[[redirects]]
from = "/api/*" # Route requests to the Express server
to = "/.netlify/functions/:splat"